### ISSUE TITLE
Custom component is not shown on the resource page

### ISSUE THREAD

**Issue by telefoniero** [bernhardh/nova-dynamic-views#10]
Hello! I've done all steps according to your instruction (applying screens), but there are no words, as it is by default.

This is NovaServiceProvider.php file.
<img width="403" alt="Снимок экрана 2022-02-01 в 11 33 31" src="https://user-images.githubusercontent.com/68998223/151936097-9d6cb0be-5b6d-436b-9629-f4ab56795795.png">
 
This is my Record's resource file.
<img width="314" alt="Снимок экрана 2022-02-01 в 11 34 04" src="https://user-images.githubusercontent.com/68998223/151936173-abc7ef6c-8e67-4b1b-a32b-c82655f30b08.png">

There is a 'watch' process working on in terminal, on my ToolbarBtn.
<img width="1113" alt="Снимок экрана 2022-02-01 в 11 34 35" src="https://user-images.githubusercontent.com/68998223/151936227-c0dcdfbc-d29f-4c1e-bac6-e430759eed77.png">

This is basic template of a component.
<img width="370" alt="Снимок экрана 2022-02-01 в 11 35 32" src="https://user-images.githubusercontent.com/68998223/151936355-f0741d2b-6fa9-4c3f-911d-2da37f17ca6d.png">

And this is Nova's Record page, there are no new components. 
<img width="1438" alt="Снимок экрана 2022-02-01 в 11 35 56" src="https://user-images.githubusercontent.com/68998223/151936403-abad0b8e-4cb9-485f-b50d-024faba65aa0.png">

Please, help!

**Comment by telefoniero** [comment]
Forgot to mention: this is MyIndexToolbarBtn.php file, so the name of the component is similar to what I use in my resource's file
<img width="387" alt="Снимок экрана 2022-02-01 в 11 37 02" src="https://user-images.githubusercontent.com/68998223/151936537-f8d3b776-9d56-41a3-a13d-2d45fcc5e6dc.png">

**Comment by telefoniero** [comment]
Here is my composer.json file in a root filder.
```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "acme/color-picker": "*",
        "acme/quantity-tracker": "*",
        "bernhardh/nova-dynamic-views": "^1.4",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/nova": "*",
        "laravel/tinker": "^1.0",
        "acme/my-index-toolbar-btn": "*"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./nova"
        },
        {
            "type": "path",
            "url": "./nova-components/ColorPicker"
        },
        {
            "type": "path",
            "url": "./nova-components/QuantityTracker"
        },
        {
            "type": "path",
            "url": "./nova-components/MyIndexToolbarBtn"
        }
    ],
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

**Comment by telefoniero** [comment]
@bernhardh, there is also no default method for custom-index-toolbar found. Idk, if I've done everything properly.

**Comment by bernhardh** [comment]
First of all: I haven't used this package nor nova for over a year. So maybe something changed in the meantime. My old installations of nova are still working with this package. But I will try to help you anyway.

What is the content of your `tools.js` file of your `MyIndexToolbarBtn`?

**Comment by bernhardh** [comment]
Maybe this helps, this is a sample component which I require like this in the `composer.json` of a test project:

```json
{
    ...
    "require": {
        "acme/custom-resource-toolbar": "*",
    },
    ...
    "repositories": [
        ...
        {
            "type": "path",
            "url": "./nova-components/CustomResourceToolbar"
        },
    ]
}
```

In the resource:

```php
    /**
     * Using the `custom-index-header` placeholder component
     *
     * @return array[]
     */
    public function customIndexToolbarComponents()
    {
        return CustomComponents::make('flex w-full justify-end items-center mx-3')
            ->addItem('custom-resource-toolbar', [
                'label' => 'Button 1'
            ])
            ->addItem('custom-resource-toolbar', [
                'label' => 'Button 2'
            ]);
    }
```

Which result to this:

![image](https://user-images.githubusercontent.com/642292/152046232-b6d54f34-5e05-4594-b2ef-b20fa3243742.png)


And attached you will find the component itself.

[CustomResourceToolbar.zip](https://github.com/bernhardh/nova-dynamic-views/files/7981735/CustomResourceToolbar.zip)

Hope this helps.

**Comment by telefoniero** [comment]
@bernhardh, hi again! There was an error on assets' compiling, which i didn't notice. There's no problem anymore. Thanks a lot for your attention!
