### ISSUE TITLE
404 in the dashboard

### ISSUE THREAD

**Issue by dsazup** [bernhardh/nova-dynamic-views#5]
Hello, we're currently seeing 404 when looking at nova dashboard. It tries to go to `https://example.com/nova-vendor/nova-dynamic-views/undefined/dashboard-header` and fails because `resourceName` is undefined in the dashboard. Other resources are working fine. Any ideas what's the best way to fix it?

**Comment by bernhardh** [comment]
I am currently at vacation. I will have a look at it on monday. Sry

**Comment by dsazup** [comment]
Of course, whenever you have a chance 🙂 also happy to submit a PR just let me know.

**Comment by bernhardh** [comment]
Fixed with `v1.4.0`. 

Please check it out and give me a feedback if this fixes your issue. Thanks

**Comment by dsazup** [comment]
Seems to be working fine now - thanks!
