### ISSUE TITLE
Conflicts with other packages using custom-*-* views

### ISSUE THREAD

**Issue by faudesabine** [bernhardh/nova-dynamic-views#7]
Am I right that this package does not work with other packages that overwrite the custom-index-header, custom-index-toolbar, custom-detail-header, custom-detail-toolbar, etc. like nova-breadcrumbs (I saw your issue https://github.com/chris-ware/nova-breadcrumbs/issues/108) or am I missing something?

Thanks 😊

**Comment by bernhardh** [comment]
Yes. You are right. These custom-*-* views are out of the box only overwriteable once. The idea of this package is to overcome these limitations, but that only works, if not only your app, but also the used other packages are using nova-dynamic-views.
