### ISSUE TITLE
Call standalone action from button

### ISSUE THREAD

**Issue by warksit** [bernhardh/nova-dynamic-views#8]
Is this possible?

**Comment by bernhardh** [comment]
Could you be a bit more specific?

**Comment by warksit** [comment]
Appologies. Am I able to call an existing action from a button. the action I have in mind is a [Standalone Action](https://nova.laravel.com/docs/3.0/actions/registering-actions.html#standalone-actions) so does not require a Model Collection

**Comment by bernhardh** [comment]
You can do in your custom vue components the exact same thing what you could do without this package.
